# permalink: /:title
# Site settings


baseurl: /my_blog

markdown: kramdown
kramdown:
  parse_block_html: true


# Build settings

title: Great New Blog Title
author:
  name: Riccardo Delli Compagni
  email: your-email@domain.com
description: "Great site about...."
