# permalink: /:title
# Site settings


#baseurl: /my_blog
source-code: https://github.com/RiccardoDC/my_blog

title: Great New Blog Title
author:
  name: Riccardo Delli Compagni
  email: your-email@domain.com
description: "Great site about...."
